[FIELDS]
default = ["battles", "WR", "avg_dmg", "avg_kills", "allies_wr", "enemies_wr"]
extra = [ "spot_rate", "top_tier", "DR", "survival", "share_alive", "battle_duration"]
team_extra = [ "allies_avg_dmg", "enemies_avg_dmg", "allies_battles", "enemies_battles"]
team_wr = [ "allied_platoon_wr", "enemy_platoon_wr", "allied_ht_wr", "enemies_ht_wr" ]
wr_diff =["wr_diff", "wr_diff_platoon", "wr_diff_ht", "wr_diff_mt", "wr_diff_lt", "wr_diff_td"] 
shots  =[ "hit_rate", "pen_rate","effective_pen_rate" ]

[FIELD.battles]
name = "Battles"
metric = "count"
fields = "exp"
# filter = "all:all" ## filter not not required for replay fields
format = ".0f"

[FIELD.WR]
name = "WR"
metric = "average_if"
fields = "battle_result=1"
format = ".1%"

[FIELD.avg_dmg]
name = "DPB"
filter = "player:default"
metric = "average"
fields = "player.damage_made"
format = ".0f"

[FIELD.avg_kills]
name = "KPB"
filter = "player:default"
metric = "average"
fields = "player.enemies_destroyed"
format = ".2f"

[FIELD.spot_rate]
name = "Spots"
filter = "player:default"
metric = "average"
fields = "player.enemies_spotted"
format = ".2f"

[FIELD.top_tier]
name = "Top tier"
metric = "average_if"
fields = "top_tier=1"
format = ".0%"

[FIELD.DR]
name = "DR"
filter = "player:default"
metric = "ratio"
fields = "player.damage_made/player.damage_received"
format = ".2f"

[FIELD.hit_rate]
name = "Hit rate"
filter = "player:default"
metric = "ratio"
fields = "player.shots_hit/player.shots_made"
format = ".0%"

[FIELD.pen_rate]
name = "Pen rate"
filter = "player:default"
metric = "ratio"
fields = "player.shots_pen/player.shots_hit"
format = ".0%"


[FIELD.effective_pen_rate]
name = "Shots pen"
filter = "player:default"
metric = "ratio"
fields = "player.shots_pen/player.shots_made"
format = "4.0%"

[FIELD.survival]
name = "Surv%"
filter = "player:default"
metric = "average_if"
fields = "player.death_reason=-1"
format = ".0%"

[FIELD.battle_duration]
name = "Duration"
metric = "average"
fields = "battle_duration"
format = ".0f"

[FIELD.share_alive]
name = "% Alive"
filter = "player:default"
metric = "ratio"
fields = "player.time_alive/battle_duration"
format = ".0%"

[FIELD.allies_wr]
name = "Allies WR"
filter = "allies:default"
metric = "average"
fields = "player.wr"
format = ".1%"

[FIELD.enemies_wr]
name = "Enemies WR"
filter = "enemies:default"
metric = "average"
fields = "player.wr"
format = ".1%"

[FIELD.wr_diff]
name = "WR diff"
metric = "difference"
filter = "allies:default"
filter2 = "enemies:default"
fields = "player.wr"
format = ".1%"

[FIELD.wr_diff_platoon]
name = "Plat WR diff"
metric = "difference"
filter = "allies:platoon"
filter2 = "enemies:platoon"
fields = "player.wr"
format = ".1%"

[FIELD.wr_diff_ht]
name = "HT WR diff"
metric = "difference"
filter = "allies:heavy_tank"
filter2 = "enemies:heavy_tank"
fields = "player.wr"
format = ".1%"

[FIELD.wr_diff_mt]
name = "MT WR diff"
metric = "difference"
filter = "allies:medium_tank"
filter2 = "enemies:medium_tank"
fields = "player.wr"
format = ".1%"


[FIELD.wr_diff_lt]
name = "LT WR diff"
metric = "difference"
filter = "allies:light_tank"
filter2 = "enemies:light_tank"
fields = "player.wr"
format = ".1%"


[FIELD.wr_diff_td]
name = "TD WR diff"
metric = "difference"
filter = "allies:tank_destroyer"
filter2 = "enemies:tank_destroyer"
fields = "player.wr"
format = ".1%"


[FIELD.allied_platoon_wr]
name = "A Plat WR"
filter = "allies:platoon"
metric = "average"
fields = "player.wr"
format = ".1%"

[FIELD.enemy_platoon_wr]
name = "E Plat WR"
filter = "enemies:platoon"
metric = "average"
fields = "player.wr"
format = ".1%"

[FIELD.allies_avg_dmg]
name = "A DPB"
filter = "allies:default"
metric = "average"
fields = "player.avgdmg"
format = ".0f"

[FIELD.enemies_avg_dmg]
name = "E DPB"
filter = "enemies:default"
metric = "average"
fields = "player.avgdmg"
format = ".0f"

[FIELD.allies_battles]
name = "A Bttls"
filter = "allies:default"
metric = "average"
fields = "player.battles"
format = ".0f"

[FIELD.enemies_battles]
name = "E Bttls"
filter = "enemies:default"
metric = "average"
fields = "player.battles"
format = ".0f"

[FIELD.allied_ht_wr]
name = "A HT WR"
filter = "allies:heavy_tank"
metric = "average"
fields = "player.wr"
format = ".1%"

[FIELD.enemies_ht_wr]
name = "E HT WR"
filter = "enemies:heavy_tank"
metric = "average"
fields = "player.wr"
format = ".1%"


[REPORTS]
default = ["total", "battle_result", "tank_tier", "mastery_badge", "avg_dmg"]
extra = ["battle_tier", "battle_mode", "solo", "battle_duration", "map", "enemy_wr", "wr_diff", "replay"]
tank = ["tank_type", "tank_nation", "is_premium"]

[REPORT.total]
name = "All battles"
categorization = "total"

[REPORT.battle_result]
name = "Result"
categorization = "category"
field = "battle_result"
categories = ["Loss", "Win", "Draw"]

[REPORT.tank_tier]
name = "Tank tier"
categorization = "category"
field = "player.tank_tier"
categories = ["-", "I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X"]

[REPORT.tank_nation]
name = "Nation"
categorization = "string"
field = "player.tank_nation"

[REPORT.tank_type]
name = "Class"
categorization = "string"
field = "player.tank_type"

[REPORT.mastery_badge]
name = "Mastery"
categorization = "category"
field = "mastery_badge"
categories = ["-", "3rd Class", "2nd Class", "1st Class", "Mastery"]

[REPORT.is_premium]
name = "Type"
categorization = "category"
field = "player.tank_is_premium"
categories = ["Tech tree", "Premium"]

[REPORT.battle_tier]
name = "Battle tier"
categorization = "number"
field = "battle_tier"

[REPORT.battle_mode]
name = "Mode"
categorization = "category"
field = "battle_type"
categories = ["Encounter", "Supremacy"]

[REPORT.solo]
name = "Platoon"
categorization = "category"
field = "solo"
categories = ["Platoon", "Solo"]


[REPORT.map]
name = "Map"
categorization = "string"
field = "map"

[REPORT.avg_dmg]
name = "Average dmg"
categorization = "bucket"
field = "player.damage_made"
buckets = [0, 1000, 1500, 2000, 2500, 3000, 4000, 5000]
bucket_labels = [
    "0 - 1000",
    "1000 - 1500",
    "1500 - 2000",
    "2000 - 2500",
    "2500 - 3000",
    "3000 - 4000",
    "4000 - 5000",
    "5000+",
]

[REPORT.enemy_wr]
name = "Enemy WR"
categorization = "bucket"
field = "player.wr"
filter = "enemies:all"
buckets = [0, 0.45, 0.475, 0.5, 0.525, 0.55, 1]
bucket_labels = [" < 45%", "45 - 47.5%", "47.5 - 50%", "50 - 52.5%", "52.5 - 55%", "> 55%", "no stats"]

[REPORT.battle_duration]
name = "Duration"
categorization = "bucket"
field = "battle_duration"
buckets = [0, 60, 120, 180, 240, 300, 360]
bucket_labels = [" < 1 min", "1 - 2 min", "2 - 3 min", "3 - 4 min", "4 - 5 min", "5 - 6 min", "6 - 7 min"]

[REPORT.replay]
name = "Replay"
categorization = "string"
field = "title_uniq"


[REPORT.wr_diff]
name = "Team WR diff"
categorization = "difference_bucket"
field = "player.wr"
filter = "allies:default"
filter2 = "enemies:all"
buckets = [-1, -0.05, -0.025, -0.01, 0.01, 0.025, 0.05]
bucket_labels = [" < -5%", "-5% - -2.5%", "-2.5% - -1%", "-1% - 1%", "1% - 2.5%", "2.5 - 5%", "> 5%"]
