[GENERAL]
reports = ["TOTAL", "battle_result", "battle_type"]

[FIELDS]
default = ["battles", "WR", "avg_dmg", "avg_kills", "spot_rate", "top_tier", "DR", "allies_wr", "enemies_wr"]
extra = ["survival", "allied_platoon_wr", "enemy_platoon_wr", "allies_avg_dmg", "enemies_avg_dmg"]

[FIELD.battles]
name = "Battles"
metric = "count"
fields = "exp"
# filter = "all:all" ## filter not not required for replay fields
format = "d"

[FIELD.WR]
name = "WR"
metric = "average_if"
fields = "battle_result=1"
format = ".1%"

[FIELD.avg_dmg]
name = "DPB"
filter = "player:default"
metric = "average"
fields = "player.damage_made"
format = ".0f"

[FIELD.avg_kills]
name = "KPB"
filter = "player:default"
metric = "average"
fields = "player.enemies_destroyed"
format = ".2f"

[FIELD.spot_rate]
name = "Spot"
filter = "player:default"
metric = "average"
fields = "player.enemies_spotted"
format = ".2f"

[FIELD.top_tier]
name = "Top tier"
metric = "average_if"
fields = "top_tier=1"
format = ".0%"

[FIELD.DR]
name = "DR"
filter = "player:default"
metric = "ratio"
fields = "player.damage_made,player.damage_received"
format = ".2f"

[FIELD.survival]
name = "Surv%"
filter = "player:default"
metric = "average_if"
fields = "player.death_reason=-1"
format = ".0%"

[FIELD.allies_wr]
name = "Allies WR"
filter = "allies:default"
metric = "average"
fields = "player.wr"
format = ".1%"

[FIELD.enemies_wr]
name = "Enemies WR"
filter = "enemies:default"
metric = "average"
fields = "player.wr"
format = ".1%"

[FIELD.allied_platoon_wr]
name = "A Plat WR"
filter = "allies:platoon"
metric = "average"
fields = "player.wr"
format = ".1%"

[FIELD.enemy_platoon_wr]
name = "E Plat WR"
filter = "enemies:platoon"
metric = "average"
fields = "player.wr"
format = ".1%"

[FIELD.allies_avg_dmg]
name = "Allies DPB"
filter = "allies:default"
metric = "average"
fields = "player.avgdmg"
format = ".0f"

[FIELD.enemies_avg_dmg]
name = "Enemies DPB"
filter = "enemies:default"
metric = "average"
fields = "player.avgdmg"
format = ".0f"


[REPORTS]
default = ["total", "battle_result", "tank_tier", "mastery_badge", "avg_dmg"]
extra = ["is_premium", "battle_tier", "map"]


[REPORT.total]
name = "All battles"
categorization = "total"

[REPORT.battle_result]
name = "Battle result"
categorization = "category"
field = "battle_result"
categories = ["Loss", "Win", "Draw"]

[REPORT.tank_tier]
name = "Tank tier"
categorization = "category"
field = "player.tank_tier"
categories = ["-", "I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X"]

[REPORT.mastery_badge]
name = "Mastery"
categorization = "category"
field = "mastery_badge"
categories = ["-", "3rd Class", "2nd Class", "1st Class", "Mastery"]

[REPORT.is_premium]
name = "Tank type"
categorization = "category"
field = "player.tank_is_premium"
categories = ["Tech tree", "Premium"]

[REPORT.battle_tier]
name = "Battle tier"
categorization = "number"
field = "battle_tier"

[REPORT.map]
name = "Map"
categorization = "string"
field = "map"

[REPORT.avg_dmg]
name = "Average dmg"
categorization = "bucket"
field = "player.damage_made"
buckets = [0, 1000, 1500, 2000, 2500, 3000, 4000, 5000]
bucket_labels = [
    "0 - 1000",
    "1000 - 1500",
    "1500 - 2000",
    "2000 - 2500",
    "2500 - 3000",
    "3000 - 4000",
    "4000 - 5000",
    "5000+",
]
