[GENERAL]
reports = ["TOTAL", "battle_result", "battle_type"]

[FIELDS]

[[FIELDS.default]]
name = "Battles"
metric = "count"
fields = "exp"
# filter = "all:all" ## filter not not required for replay fields
format = "d"

[[FIELDS.default]]
name = "WR"
metric = "average_if"
fields = "battle_result=1"
format = ".1%"

[[FIELDS.default]]
name = "DPB"
filter = "player:default"
metric = "average"
fields = "player.damage_made"
format = ".0f"

[[FIELDS.default]]
name = "KPB"
filter = "player:default"
metric = "average"
fields = "player.enemies_destroyed"
format = ".2f"

[[FIELDS.default]]
name = "Spot"
filter = "player:default"
metric = "average"
fields = "player.enemies_spotted"
format = ".2f"

[[FIELDS.default]]
name = "Top tier"
metric = "average_if"
fields = "top_tier=1"
format = ".0%"

[[FIELDS.default]]
name = "DR"
filter = "player:default"
metric = "ratio"
fields = "player.damage_made,player.damage_received"
format = ".2f"

[[FIELDS.default]]
name = "Surv%"
filter = "player:default"
metric = "average_if"
fields = "player.death_reason=-1"
format = ".0%"

[[FIELDS.default]]
name = "Allies WR"
filter = "allies:default"
metric = "average"
fields = "player.wr"
format = ".1%"

[[FIELDS.default]]
name = "Enemies WR"
filter = "enemies:default"
metric = "average"
fields = "player.wr"
format = ".1%"

[[FIELDS.extra]]
name = "A Plat WR"
filter = "allies:platoon"
metric = "average"
fields = "player.wr"
format = ".1%"

[[FIELDS.extra]]
name = "E Plat WR"
filter = "enemies:platoon"
metric = "average"
fields = "player.wr"
format = ".1%"

[[FIELDS.extra]]
name = "Allies DPB"
filter = "allies:default"
metric = "average"
fields = "player.avgdmg"
format = ".0f"

[[FIELDS.extra]]
name = "Enemies DPB"
filter = "enemies:default"
metric = "average"
fields = "player.avgdmg"
format = ".0f"


[REPORTS]
default = ["total", "battle_result", "mastery_badge"]
extra = ["is_premium"]


[REPORT.total]
name = "All battles"
categorization = "total"

[REPORT.battle_result]
name = "Battle result"
categorization = "category"
field = "battle_result"
categories = ["Loss", "Win", "Draw"]

[REPORT.mastery_badge]
name = "Mastery"
categorization = "category"
field = "mastery_badge"
categories = ["-", "3rd Class", "2nd Class", "1st Class", "Mastery"]

[REPORT.is_premium]
name = "Tank type"
categorization = "category"
field = "player.tank.is_premium"
categories = ["Tech tree", "Premium"]
